use_frameworks!

target 'TheFeedComponent_Example' do
  pod 'TheFeedComponent', :path => '../'

  target 'TheFeedComponent_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
    pod 'Nimble', '~> 5.0'
  end
end
